---
swagger: "2.0"
info:
  version: "0.0.0"
  title: "Ticket Dispute API"
paths:
  /cases:
    get:
      tags:
      - "case"
      description: "Gets `case` objects."
      operationId: "getCases"
      parameters:
      - name: "userId"
        in: "query"
        description: "Identity of a user"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful response"
          schema:
            type: "array"
            title: "ArrayOfCases"
            items:
              $ref: "#/definitions/inline_response_200"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/inline_response_default"
      x-swagger-router-controller: "Case"
    post:
      tags:
      - "case"
      description: "Creates a new case for this user"
      operationId: "addCase"
      parameters:
      - in: "body"
        name: "case"
        description: "Case too add"
        required: true
        schema:
          $ref: "#/definitions/case"
      responses:
        200:
          description: "case response"
          schema:
            $ref: "#/definitions/inline_response_200"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/inline_response_default"
      x-swagger-router-controller: "Case"
  /cases/{id}:
    get:
      tags:
      - "case"
      description: "Returns a case based on a single ID"
      operationId: "getCaseById"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of case to fetch"
        required: true
        type: "integer"
      responses:
        200:
          description: "case response"
          schema:
            $ref: "#/definitions/inline_response_200"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/inline_response_default"
      x-swagger-router-controller: "Case"
  /quotes:
    get:
      tags:
      - "quotes"
      description: "Gets `quote` objects."
      operationId: "quotesGET"
      parameters:
      - name: "caseId"
        in: "query"
        description: "Related case"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful response"
          schema:
            type: "array"
            title: "ArrayOfPersons"
            items:
              $ref: "#/definitions/inline_response_200_1"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/inline_response_default"
      x-swagger-router-controller: "Quotes"
    post:
      tags:
      - "quotes"
      description: "Creates a new quote for this case"
      operationId: "addQuote"
      parameters:
      - in: "body"
        name: "quote"
        description: "Quote too add"
        required: true
        schema:
          $ref: "#/definitions/quote"
      responses:
        200:
          description: "quote response"
          schema:
            $ref: "#/definitions/inline_response_200_1"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/inline_response_default"
      x-swagger-router-controller: "Quotes"
  /quotes/{id}:
    get:
      tags:
      - "quotes"
      description: "Returns a quote based on a single ID"
      operationId: "getQuoteById"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of quote to fetch"
        required: true
        type: "integer"
      responses:
        200:
          description: "quote response"
          schema:
            $ref: "#/definitions/inline_response_200_1"
        default:
          description: "unexpected error"
          schema:
            $ref: "#/definitions/inline_response_default"
      x-swagger-router-controller: "Quotes"
definitions:
  Case:
    type: "object"
    required:
    - "id"
    properties:
      status:
        type: "string"
        description: "The status of the case."
      time:
        type: "string"
        format: "date-time"
        description: "The datetime that the case was happened."
      location:
        type: "string"
        description: "The location where this case happened."
      speed:
        type: "integer"
        description: "The speed when you are driving."
      images:
        type: "array"
        description: "Uploaded image"
        items:
          type: "string"
      quotes:
        type: "array"
        description: "All quotes get from lawyer for this case"
        items:
          type: "integer"
      id:
        type: "integer"
        format: "int64"
  NewCase:
    type: "object"
    properties:
      status:
        type: "string"
        description: "The status of the case."
      time:
        type: "string"
        format: "date-time"
        description: "The datetime that the case was happened."
      location:
        type: "string"
        description: "The location where this case happened."
      speed:
        type: "integer"
        description: "The speed when you are driving."
      images:
        type: "array"
        description: "Uploaded image"
        items:
          type: "string"
      quotes:
        type: "array"
        description: "All quotes get from lawyer for this case"
        items:
          type: "integer"
  Quote:
    type: "object"
    required:
    - "id"
    properties:
      _id:
        type: "number"
        description: "A unique identifier of the quote. Automatically assigned by\
          \ the API when the quote is created."
      lawyer:
        $ref: "#/definitions/quotes_lawyer"
      price:
        type: "number"
        format: "float"
        description: "The price this lawyer offered for this case"
      caseId:
        type: "integer"
        description: "Related case id"
      id:
        type: "integer"
        format: "int64"
  NewQuote:
    type: "object"
    properties:
      _id:
        type: "number"
        description: "A unique identifier of the quote. Automatically assigned by\
          \ the API when the quote is created."
      lawyer:
        $ref: "#/definitions/quotes_lawyer"
      price:
        type: "number"
        format: "float"
        description: "The price this lawyer offered for this case"
      caseId:
        type: "integer"
        description: "Related case id"
  Lawyer:
    type: "object"
    properties:
      _id:
        type: "number"
        description: "lawyer id"
      name:
        type: "string"
        description: "lawyer name"
      phone:
        type: "string"
        description: "phone number"
      email:
        type: "string"
        description: "lawyer ema"
  Error:
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
  inline_response_200:
    required:
    - "id"
    properties:
      status:
        type: "string"
        description: "The status of the case."
      time:
        type: "string"
        format: "date-time"
        description: "The datetime that the case was happened."
      location:
        type: "string"
        description: "The location where this case happened."
      speed:
        type: "integer"
        description: "The speed when you are driving."
      images:
        type: "array"
        description: "Uploaded image"
        items:
          type: "string"
      quotes:
        type: "array"
        description: "All quotes get from lawyer for this case"
        items:
          type: "integer"
      id:
        type: "integer"
        format: "int64"
  inline_response_default:
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
  case:
    type: "object"
    properties:
      status:
        type: "string"
        description: "The status of the case."
      time:
        type: "string"
        format: "date-time"
        description: "The datetime that the case was happened."
      location:
        type: "string"
        description: "The location where this case happened."
      speed:
        type: "integer"
        description: "The speed when you are driving."
      images:
        type: "array"
        description: "Uploaded image"
        items:
          type: "string"
      quotes:
        type: "array"
        description: "All quotes get from lawyer for this case"
        items:
          type: "integer"
  quotes_lawyer:
    properties:
      _id:
        type: "number"
        description: "lawyer id"
      name:
        type: "string"
        description: "lawyer name"
      phone:
        type: "string"
        description: "phone number"
      email:
        type: "string"
        description: "lawyer ema"
  inline_response_200_1:
    required:
    - "id"
    properties:
      _id:
        type: "number"
        description: "A unique identifier of the quote. Automatically assigned by\
          \ the API when the quote is created."
      lawyer:
        $ref: "#/definitions/quotes_lawyer"
      price:
        type: "number"
        format: "float"
        description: "The price this lawyer offered for this case"
      caseId:
        type: "integer"
        description: "Related case id"
      id:
        type: "integer"
        format: "int64"
  quote:
    type: "object"
    properties:
      _id:
        type: "number"
        description: "A unique identifier of the quote. Automatically assigned by\
          \ the API when the quote is created."
      lawyer:
        $ref: "#/definitions/quotes_lawyer"
      price:
        type: "number"
        format: "float"
        description: "The price this lawyer offered for this case"
      caseId:
        type: "integer"
        description: "Related case id"
